### ISSUE TITLE
Feature request: Formatting enhancement

### ISSUE THREAD

**Issue by JohOply** [axemwa/NoStrip#13]
Hi, it's me again :D

I have 2 minor features request:

- Add support for to create a new line with \n in messages
- Remove the space after the prefix inplugin files, to be able to remove entirly the prefix (explanations below)

**About the space:** 
There is a space which needs to be removed, to be fully customizable :)
In my config, there is no space. So if I want to remove prefix, there is a useless space

https://i.imgur.com/gdGXPhn.png with this config
```
messages:
  prefix: '[Random Prefix]'
  config-reloaded: '&6&l(!)&r &eConfig Reloaded!'
```

and https://i.imgur.com/csToAvu.png with this config 
```
messages:
  prefix: ''
  config-reloaded: '&6&l(!)&r &eConfig Reloaded!'
```

**Comment by axemwa** [comment]
Sure I'll look into it soon thanks for picking that up

**Comment by axemwa** [comment]
Btw just so you know you can use this formatting to add new lines atm but I will still add the \n placeholder anyway
Example:
![image](https://user-images.githubusercontent.com/37608633/63652055-0c326b80-c79b-11e9-9f13-95625fde2ace.png)

**Comment by axemwa** [comment]
Turns out \n already works to add new lines you just have to use double quotes instead of single quotes in the config message that you want to have a newline which results in the above message formatting
eg

instead of

no-axe-permission: **'Sorry you can not do that here\nTry again later'**

do

no-axe-permission: **"Sorry you can not do that here\nTry again later"**

**Comment by axemwa** [comment]
Removed the spaces after the prefix in code, new release is out.
https://www.spigotmc.org/resources/%E2%A6%B8nostrip%E2%A6%B8.61574/
